Styling bookstore
Rifat8080/Bookstore-React-App pull request #5
Opened 2023-07-18 03:43 UTC by Rifat8080

- Add any missing JSX elements to your project (without adding extra functionality)

- Your final design should match Zeplin's design (this includes all elements + the same styling)

- You may use the CSS rules detailed in Zeplin to style the website.

2023-07-18 04:23 UTC, topeogunleye requested changes
Hi @Rifat8080, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Try-Again](https://user-images.githubusercontent.com/52934128/180646051-aed7efa6-6d15-4853-9962-73186e366f2c.gif)

> ## (Highlights) Good Points: 💪 
✅ No !important overusing: Avoid excessive use of the !important declaration, as it can lead to specificity and maintainability issues.

✅ No inefficient selectors: Use efficient CSS selectors to target elements without adding unnecessary complexity or performance overhead.

✅ No inline styling: Inline styling should be avoided, except for React inline styling where a variable is created and passed to the React style prop.
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
👉 One optional suggestion for improvement is to follow the convention for naming your branch. Usually, branch names should use the past tense verb to indicate that the feature has been implemented. For example, instead of `Styling-Bookstore`, you could use `Styled-Bookstore`. This would make your branch name more consistent and clear for future pull requests.

- [ ]  Next time, and for future commits, I kindly suggest that you please make use of imperative mood in the subject line for your commit messages.
:x: Bad Commit Messages :x:
<img width="136" alt="image" src="https://github.com/Rifat8080/Bookstore-React-App/assets/52934128/7d5daccc-9e34-454e-bf1f-0bff224db445">

### ✔️ Good Commit Messages: ✔️
✔️  Add fix for dark mode toggle state
✔️  Update README file.
✔️  Add styles to h1.

- [ ] Please refer to this article: please read it and apply it in your work from now on: [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md);

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-18 04:23 UTC, topeogunleye commented on src/styles/BookList.css
> +.Oval-2 {
Thank you for your work on this feature. I have a few suggestions to make it more consistent with the Zeplin design.
- Please use a circular shape for the progress bar, as shown in the design. This will make it look more elegant and user-friendly.
- Please add a light gray border to the right of the Comment and Remove buttons, as seen in the design. This will create a clear separation between the buttons and the rest of the UI.

I hope these suggestions are helpful. Please let me know if you have any questions or concerns. 😊



|   |  |
| ------------- | ------------- |
| Your Design  | <img width="893" alt="image" src="https://github.com/Rifat8080/Bookstore-React-App/assets/52934128/4fd98541-cec5-42ad-9fd9-719d30a04fa1">  |
| Zeplin Design  | <img width="699" alt="image" src="https://github.com/Rifat8080/Bookstore-React-App/assets/52934128/974e0cc8-4328-4775-beb3-91884fbe4eb2">  |

2023-07-18 04:23 UTC, topeogunleye commented on src/components/Navbar.js
>  const Navbar = () => (
- [ ] The person icon seems to not be displayed on the browser. 


|  |   |
| ------------- | ------------- |
| Your Design | <img width="929" alt="image" src="https://github.com/Rifat8080/Bookstore-React-App/assets/52934128/6575ef0f-6207-409b-b2b6-b486227315e3">  |
| Zeplin Design  | <img width="807" alt="image" src="https://github.com/Rifat8080/Bookstore-React-App/assets/52934128/ad0945a7-a193-4b3c-86f1-e5f4e73a7f8c">  |

2023-07-18 05:50 UTC, CollinsTatang approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- You meet all the requested changes. :heavy_check_mark: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-18 06:06 UTC, merged

2023-09-28 07:37 UTC, Ibizugbe reviewed
Hi @Rifat8080 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have already submitted a [PR](https://github.com/Rifat8080/Bookstore-React-App/pull/10) that is under review. for consistency reasons, I suggest you work with that same link.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-10-03 06:15 UTC, binhussen reviewed
Hi @Rifat8080 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- Sticked Given Design ✔️
- Well Structured Code ✔️
- Used Git flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._